[logging]
level = "INFO" # DEBUG, INFO, WARNING, ERROR, or CRITICAL

[matrix]
homeserver = "https://matrix.example.org"
access_token = "YOUR_MATRIX_ACCESS_TOKEN"

[meshcore]
serial_port = "/dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_44:1B:F6:6F:15:68-if00"

[[sync]]
matrix_room_id = "!Phel3ohTh5quie7fee:example.org"
meshcore_channel_idx = 1
